# Build Workflow

name: Build with Gradle

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'

  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || format('{0}-{1}', github.ref, github.run_number) }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      JAVA_HOME: '/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/21.0.5-11/x64'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: actions/cache@v4
        id: cache
        with:
          path: |
            ~/.gradle/*
            **/gradle-wrapper.properties
            **/loom-cache
            **/prebundled-jars
            ${{ env.JAVA_HOME }}
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-


      - name: Set up JDK 21
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: 'gradle'

      - name: Chmod Gradle
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build --no-daemon

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: versions/**/build/libs/*.jar